import TripPass from './trip-pass';
import {useEffect,useRef,useState} from 'react';
import {Sparkles,Trash2} from 'lucide-react';
import {supabase} from './supabase';
import {type Trip,type AIPlan,destinations,shortDate,addDays} from './travel-data';
export default function AIPlanner({trip,onChange,onLogin}:{trip:Trip;onChange:(t:Trip)=>void;onLogin:()=>void}){
 const [pace,setPace]=useState('seimbang'),[interests,setInterests]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[preview,setPreview]=useState<AIPlan|null>(null),[remaining,setRemaining]=useState<number|null>(null);
 const current=useRef(trip);current.current=trip;const controller=useRef<AbortController|null>(null);
 useEffect(()=>()=>controller.current?.abort(),[]);
 const city=trip.destinationMeta?.city||destinations.find(d=>d.id===trip.destination)?.city||trip.destination;
 const country=trip.destinationMeta?.country||destinations.find(d=>d.id===trip.destination)?.country||'';
 const plan=preview||trip.aiPlan;
 async function generate(){
  if(!supabase){setError('Koneksi akun belum dikonfigurasi.');return;}
  const {data}=await supabase.auth.getSession();if(!data.session){onLogin();return;}
  const snapshot=trip;setBusy(true);setError('');setPreview(null);controller.current=new AbortController();
  try{const r=await fetch('/api/itinerary',{method:'POST',signal:controller.current.signal,headers:{'Content-Type':'application/json',Authorization:`Bearer ${data.session.access_token}`},body:JSON.stringify({city,country,start:trip.start,days:trip.days,people:trip.people,budget:trip.budget,pace,interests,arrival:trip.flight?.arrive,arrivalDay:trip.flight?.arrivalDay,returnAt:trip.flight?.returnAt,oneWay:trip.journey==='oneway',locked:trip.items.filter(x=>x.paid).map(x=>({day:x.day,time:x.time,title:x.title}))})});const body=await r.json();if(!r.ok)throw Error(body.error||'Gagal membuat rekomendasi.');if(current.current!==snapshot)throw Error('Perjalanan berubah saat AI bekerja. Buat ulang agar sesuai pilihan terbaru.');setPreview(body.plan);setRemaining(body.access?.remaining??null);}catch(e){if(e instanceof Error&&e.name!=='AbortError')setError(e.message);}finally{setBusy(false);}
 }
 function edit(id:string,values:Partial<AIPlan['activities'][number]>){if(!plan)return;const next={...plan,activities:plan.activities.map(a=>a.id===id?{...a,...values}:a)};if(preview)setPreview(next);else onChange({...trip,aiPlan:next});}
 const stale=plan&&(plan.context.city!==city||plan.context.start!==trip.start||plan.context.days!==trip.days||plan.context.people!==trip.people||plan.context.budget!==trip.budget);
 return <section className="ai-planner"><div className="eyebrow"><Sparkles size={16}/> ASISTEN PERJALANAN</div><h2>Buatkan rencana di {city}</h2><p>Rekomendasi wisata, tempat makan, dan area menginap berdasarkan pencarian referensi. Sesuaikan dulu, lalu simpan bersama perjalananmu.</p><div className="ai-plan-access"><strong>Basic · Gratis</strong><p>1 perjalanan · maksimal 2 permintaan AI per akun. Mengedit dan menyimpan rancangan tidak memakai kuota.</p>{remaining!==null&&<p>Sisa permintaan: {remaining}</p>}<small>Permintaan yang diterima server memakai kuota, termasuk jika layanan AI kemudian gagal. Perjalanan ditentukan dari kota awal dan tanggal keberangkatan.</small><TripPass trip={trip} onLogin={onLogin}/></div><div className="ai-controls"><label>Budget total / orang (Rp)<input type="number" min="0" max="1000000000" value={trip.budget} onChange={e=>{const n=Number(e.target.value);if(Number.isFinite(n)&&n>=0&&n<=1e9)onChange({...trip,budget:n});}}/></label><label>Ritme perjalanan<select value={pace} onChange={e=>setPace(e.target.value)}><option value="santai">Santai</option><option value="seimbang">Seimbang</option><option value="padat">Banyak eksplorasi</option></select></label><label>Minat / kebutuhan (opsional)<input maxLength={300} value={interests} onChange={e=>setInterests(e.target.value)} placeholder="Wisata gratis, kuliner, alam…"/></label></div><button className="primary" disabled={busy} onClick={generate}>{busy?'Mencari referensi dan menyusun…':'Buat rekomendasi itinerary'}</button>{busy&&<button className="text-action" onClick={()=>controller.current?.abort()}>Batalkan</button>}<p className="inline-note">Memerlukan login. Jam adalah usulan; cek jam buka dan rute sebelum berangkat. Harga dan ketersediaan belum diperiksa melalui API pemesanan.</p>{error&&<p role="alert" className="city-warning">{error}</p>}
 {plan&&<div className="ai-result"><h3>{preview?'Pratinjau rekomendasi':'Rancangan rekomendasi tersimpan'}</h3>{stale&&<p className="city-warning">Pilihan perjalanan berubah. Buat ulang rekomendasi sebelum menggunakannya.</p>}<p>{plan.summary}</p><p><strong>Biaya rancangan belum dihitung dalam total anggaran.</strong> Integrasi hotel, tiket wisata, dan transportasi akan melengkapi penawaran setelah akses API tersedia.</p>{Array.from({length:trip.days},(_,i)=>i+1).map(day=><div key={day} className="ai-day"><h4>Hari {day} · {shortDate(addDays(trip.start,day-1))}</h4>{plan.activities.filter(a=>a.day===day).map(a=><article key={a.id} className="ai-activity"><input aria-label={'Jam '+a.title} type="time" value={a.time} onChange={e=>edit(a.id,{time:e.target.value})}/><div><small>{a.category}</small><input aria-label="Nama aktivitas rekomendasi" maxLength={160} value={a.title} onChange={e=>edit(a.id,{title:e.target.value})}/><p>{a.note}</p><a href={a.sourceUrl} target="_blank" rel="noopener noreferrer">Referensi awal</a><span> · </span><a href={'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(a.title+' '+city)} target="_blank" rel="noopener noreferrer">Cari lokasi</a><p className="inline-note">Harga belum tersedia · perubahan nama perlu pemeriksaan referensi ulang.</p></div><button className="icon-button" aria-label={'Hapus '+a.title} onClick={()=>{const next={...plan,activities:plan.activities.filter(x=>x.id!==a.id)};if(preview)setPreview(next);else onChange({...trip,aiPlan:next});}}><Trash2 size={16}/></button></article>)}</div>)}{preview&&<button className="primary" disabled={!!stale} onClick={()=>{onChange({...trip,aiPlan:preview});setPreview(null);}}>Gunakan rancangan ini</button>}<p className="inline-note">{preview?'Tinjau lalu gunakan rancangan.':'Klik Simpan itinerary untuk menyimpan perubahan ke akun.'} Tiket dan item booking yang sudah ada tetap dipertahankan.</p></div>}
 </section>;
}
