import {journeyOptions} from './transport-data';
import {destinations,geoData,Geo,Item,Trip,addDays,dayDiff} from './travel-data';
export type Place={name:string;geo:Geo;category:string;price:number;url?:string;shared?:boolean};
export type City={id:string;name:string;country:string;center:Geo;night:number;places:Place[]};
const point=(name:string,lat:number,lng:number,category:string,price:number):Place=>({name,geo:{lat,lng},category,price});
export const cities:City[]=[...destinations.map(d=>({id:d.id,name:d.city,country:d.country,center:geoData[d.id].hotel.geo,night:d.night,places:[...d.places.map((name,i)=>({name,geo:geoData[d.id].visits[i],category:'Wisata',price:d.id==='bkk'&&i<2?100000:0})),...geoData[d.id].meals.filter((m,i,a)=>a.findIndex(n=>n.name===m.name)===i).map(m=>({name:m.name,geo:m.geo,category:'Makan',price:m.price})),{name:geoData[d.id].hotel.name,geo:geoData[d.id].hotel.geo,category:'Penginapan',price:d.night,url:geoData[d.id].hotel.url,shared:geoData[d.id].hotel.shared}]})),
{id:'melaka',name:'Melaka',country:'Malaysia',center:{lat:2.195,lng:102.249},night:380000,places:[point('Dutch Square',2.1947,102.2492,'Wisata',0),point('St Paul’s Hill',2.1924,102.2503,'Wisata',0),point('Jonker Street',2.1965,102.2474,'Wisata',0),point('Area kuliner Jonker Street',2.1965,102.2474,'Makan',55000),point('Area kuliner Jalan Kota',2.1918,102.2506,'Makan',45000),{...point('Area penginapan pusat Melaka',2.195,102.249,'Penginapan',380000),shared:true}]},
{id:'penang',name:'George Town · Penang',country:'Malaysia',center:{lat:5.4141,lng:100.3288},night:420000,places:[point('Armenian Street',5.4146,100.3375,'Wisata',0),point('Chew Jetty',5.4127,100.3398,'Wisata',0),point('Gurney Drive Hawker Centre',5.4401,100.3093,'Makan',55000),point('Little India George Town',5.4169,100.339,'Makan',45000),{...point('Area penginapan George Town',5.4141,100.3288,'Penginapan',420000),shared:true}]},
{id:'ayutthaya',name:'Ayutthaya',country:'Thailand',center:{lat:14.3566,lng:100.5684},night:360000,places:[point('Wat Mahathat Ayutthaya',14.3569,100.5675,'Wisata',40000),point('Wat Chaiwatthanaram',14.3431,100.5413,'Wisata',40000),point('Chao Phrom Market',14.3596,100.5784,'Makan',45000),point('Area kuliner kota tua Ayutthaya',14.357,100.568,'Makan',50000),{...point('Area penginapan kota tua Ayutthaya',14.3566,100.5684,'Penginapan',360000),shared:true}]}];
cities.push(
{id:'putrajaya',name:'Putrajaya',country:'Malaysia',center:{lat:2.9264,lng:101.6964},night:420000,places:[point('Dataran Putra',2.9364,101.6918,'Wisata',0),point('Putrajaya Botanical Garden',2.943,101.696,'Wisata',0),point('Area kuliner Presint 8',2.93,101.674,'Makan',45000),{...point('Area penginapan Putrajaya',2.9264,101.6964,'Penginapan',420000),shared:true}]},
{id:'shahalam',name:'Shah Alam',country:'Malaysia',center:{lat:3.0738,lng:101.5183},night:380000,places:[point('Taman Tasik Shah Alam',3.0733,101.5176,'Wisata',0),point('Laman Seni 7',3.0678,101.4912,'Wisata',0),point('Area kuliner Seksyen 7',3.067,101.489,'Makan',45000),{...point('Area penginapan Shah Alam',3.0738,101.5183,'Penginapan',380000),shared:true}]},
{id:'nonthaburi',name:'Nonthaburi',country:'Thailand',center:{lat:13.842,lng:100.493},night:400000,places:[point('Museum of Nonthaburi',13.842,100.492,'Wisata',30000),point('Chaloem Kanchanaphisek Park',13.861,100.483,'Wisata',0),point('Area kuliner Nonthaburi Pier',13.843,100.491,'Makan',45000),{...point('Area penginapan Nonthaburi',13.842,100.493,'Penginapan',400000),shared:true}]});
export const cityById=(id:string)=>cities.find(c=>c.id===id)!;
export function cityAt(t:Trip,day:number){return cityById(t.cityDays?.[day-1]||t.destination)||cityById(t.destination)}
export function hotelAt(t:Trip,day:number){const date=addDays(t.start,day-1);return t.items.find(x=>x.category==='Penginapan'&&x.geo&&(x.checkin||t.start)<=date&&(x.checkout||addDays(t.start,t.days-1))>date)}
const distance=(a:Geo,b:Geo)=>{const r=Math.PI/180,x=(a.lat-b.lat)*r,y=(a.lng-b.lng)*r;const z=Math.sin(x/2)**2+Math.cos(a.lat*r)*Math.cos(b.lat*r)*Math.sin(y/2)**2;return 6371*2*Math.atan2(Math.sqrt(z),Math.sqrt(1-z))};
// Choose a catalog stay/area near the last visit and next visit in the same city.
// Coordinates and budget remain estimates; this never claims live room inventory.
export function recommendStay(city:City,items:Item[],day:number){
 const visits=items.filter(x=>x.category==='Wisata'&&x.cityId===city.id&&x.geo&&x.day>=day-1&&x.day<=day+1&&distance(x.geo,city.center)<100).sort((a,b)=>a.day-b.day||a.time.localeCompare(b.time));
 const before=visits.filter(x=>x.day<=day).at(-1),after=visits.find(x=>x.day>day);
 let anchors=[before,after].filter((x):x is Item=>!!x);
 if(!anchors.length)anchors=city.places.filter(p=>p.category==='Wisata').slice(0,2).map((p,i)=>({id:'anchor-'+i,title:p.name,category:'Wisata',price:0,paid:false,day,time:'',note:'',geo:p.geo}));
 const lodging=city.places.filter(p=>p.category==='Penginapan');
 if(!lodging.length)throw Error('Rekomendasi penginapan kota ini belum tersedia.');
 const score=(p:Place)=>anchors.reduce((sum,a)=>sum+distance(p.geo,a.geo!),0);
 let place=[...lodging].sort((a,b)=>score(a)-score(b))[0];
 if(place.name.startsWith('Area penginapan')&&anchors.length){
  const geo={lat:anchors.reduce((n,a)=>n+a.geo!.lat,0)/anchors.length,lng:anchors.reduce((n,a)=>n+a.geo!.lng,0)/anchors.length};
  place={...place,geo,name:'Area penginapan '+city.name+' dekat rute wisata'};
 }
 const distances=anchors.map(a=>a.title+' ± '+distance(place.geo,a.geo!).toFixed(1)+' km').join('; ');
 return {place,note:'1 malam · anggaran estimasi, bukan tarif/ketersediaan live. '+(place.name.startsWith('Area penginapan')?'Area pencarian, bukan hotel terverifikasi. ':'Pilihan katalog terbatas; bukan hasil pencarian hotel live. ')+(distances?'Acuan wisata sebelum/sesudah: '+distances+'. Jarak garis lurus, bukan jarak jalan.':'Lokasi awal memakai pusat kota.')};
}
export function reviseCities(t:Trip,from:number,to:number,cityId:string){
 const city=cityById(cityId);if(!city||from<1||to>t.days||from>to)throw Error('Pilih kota dan rentang hari yang valid.');
 const cityDays=Array.from({length:t.days},(_,i)=>i+1>=from&&i+1<=to?cityId:cityAt(t,i+1).id);
 if(cityDays[0]!==t.destination)throw Error('Hari kedatangan harus tetap di kota penerbangan awal. Pilih mulai hari kedua.');
 if(t.journey!=='oneway'&&cityDays[t.days-1]!==t.destination)throw Error('Tiket PP kembali dari kota awal. Akhiri perjalanan di kota awal, atau mulai pencarian dengan tiket sekali jalan.');
 for(let day=from;day<=to;day++){if(cityDays[day-1]===cityAt(t,day).id)continue;const date=addDays(t.start,day-1);if(t.items.some(x=>x.paid&&x.category!=='Pesawat'&&(x.day===day||x.category==='Penginapan'&&(x.checkin||t.start)<=date&&(x.checkout||addDays(t.start,t.days-1))>date)))throw Error('Ada booking dibayar pada hari yang berubah kota. Sesuaikan booking tersebut terlebih dahulu.');}
 if(t.items.some(x=>x.returnLeg&&x.paid)&&cityDays[t.days-1]!==cityAt(t,t.days).id)throw Error('Kota terakhir terkunci oleh tiket pulang yang sudah dibayar.');
 if(cityDays.every((id,i)=>id===cityAt(t,i+1).id))return t;
 const affected=new Set(Array.from({length:to-from+1},(_,i)=>from+i));if(to<t.days&&cityDays[to-1]!==cityAt(t,to).id&&t.dayPlans?.[String(to+1)])affected.add(to+1);
 const dayPlans=Object.fromEntries(Object.entries(t.dayPlans||{}).filter(([d])=>!affected.has(+d)));const localTransportDays=(t.localTransportDays||[]).filter(d=>!affected.has(d));
 // Retain paid records exactly; replace day recommendations, unbooked lodging and transport with one consistent plan.
 const items:Item[]=t.items.filter(x=>!(x.returnLeg&&!x.paid&&cityDays[t.days-1]!==cityAt(t,t.days).id)).filter(x=>x.paid||x.category==='Pesawat'||((x.dayPlan||x.routeKey)&&!affected.has(x.day))||(!['Penginapan','Transportasi'].includes(x.category)&&!affected.has(x.day))).map(x=>x.paid?x:({...x,cityId:x.cityId||cityAt(t,x.day).id}));
 for(const day of affected){const c=cityById(cityDays[day-1]);const visits=c.places.filter(x=>x.category==='Wisata').slice(0,2),meals=c.places.filter(x=>x.category==='Makan');visits.forEach((p,i)=>{if(items.some(x=>x.paid&&x.day===day&&(x.place||x.title)===p.name))return;items.push({id:`city-visit-${day}-${i}`,cityId:c.id,title:p.name,place:p.name,geo:p.geo,category:'Wisata',price:p.price,paid:false,day,time:i===0?'11:00':'15:00',generated:true,note:'Rekomendasi baru sesuai kota. Sesuaikan dengan durasi perpindahan, jam penerbangan dan jam buka.'})});for(let m=0;m<3;m++){if((day===1&&m===0)||(day===t.days&&m===2))continue;const p=meals[m%meals.length];if(items.some(x=>x.paid&&x.category==='Makan'&&x.day===day&&x.time===['08:00','12:30','18:30'][m]))continue;items.push({id:`city-meal-${day}-${m}`,cityId:c.id,title:`${['Sarapan','Makan siang','Makan malam'][m]} · ${p.name}`,place:p.name,geo:p.geo,category:'Makan',price:p.price,paid:false,day,time:['08:00','12:30','18:30'][m],generated:true,note:'Anggaran contoh per orang. Periksa gerai, menu dan jam buka.'})}}
 // Preserve hotel choices night by night where the city still matches.
 for(let day=1;day<t.days;day++){const date=addDays(t.start,day-1),c=cityById(cityDays[day-1]);const existing=hotelAt(t,day);if(existing?.paid)continue;if(existing&&(existing.cityId||cityAt(t,day).id)===c.id){const nights=Math.max(1,dayDiff(existing.checkin||t.start,existing.checkout||addDays(t.start,t.days-1)));items.push({...existing,id:`stay-${day}`,day,time:day===existing.day?existing.time:'15:00',checkin:date,checkout:addDays(date,1),price:existing.price/nights,cityId:c.id});}else{const recommendation=recommendStay(c,items,day);const h=recommendation.place;items.push({id:`stay-${day}`,title:h.name,place:h.name,cityId:c.id,category:'Penginapan',geo:h.geo,bookingUrl:h.url,price:c.night*(h.shared?Math.ceil(t.people/2):1),shared:h.shared,paid:false,day,time:'15:00',checkin:date,checkout:addDays(date,1),generated:true,note:recommendation.note});}}
 for(let day=1;day<=t.days;day++){if(dayPlans[String(day)])continue;const c=cityById(cityDays[day-1]);if(day===1){items.push({id:'city-transfer-1',cityId:c.id,title:`Bandara kedatangan → ${c.name}`,category:'Transportasi',price:80000,paid:false,day,time:'',generated:true,note:'Cadangan transfer kedatangan; simulasi.'});continue;}const prev=cityById(cityDays[day-2]);if(prev.id!==c.id){const opt=journeyOptions(prev,c)[0];items.push({id:`city-transfer-${day}`,cityId:c.id,fromCity:prev.id,toCity:c.id,mode:opt.id,minutes:opt.minutes,title:`${prev.name} → ${c.name}`,category:'Transportasi',price:opt.price,paid:false,day,time:'08:00',generated:true,note:`${opt.name} · ± ${opt.minutes} menit · ${opt.detail}`});}}
 if(t.journey!=='oneway'||items.some(x=>x.returnLeg)){items.push({id:'city-return',cityId:cityDays[t.days-1],title:'Transfer menuju bandara pulang',category:'Transportasi',price:80000,paid:false,day:t.days,time:'',generated:true,note:'Cadangan menuju bandara pulang; pastikan sesuai kota tiket pulang.'});}
 items.push({id:'city-local',title:'Transportasi lokal selama perjalanan',category:'Transportasi',price:30000*(t.days-localTransportDays.length),reserveOriginal:30000*t.days,paid:false,day:1,time:'',generated:true,note:'Cadangan lokal per orang; di luar transfer antarkota.'});
 // Paid transport is retained instead of recreating the same generated segment.
 const deduped=items.filter((x,i)=>!x.generated||!items.some((y,j)=>j!==i&&y.paid&&(y.id===x.id||y.category===x.category&&y.day===x.day&&y.title===x.title)));
 return {...t,cityDays,dayPlans,localTransportDays,items:deduped};
}
