import {Trip,Item,money} from './travel-data';
import {cityAt,cityById} from './cities';
import {journeyOptions} from './transport-data';
export const clock=(m:number)=>`${String(Math.floor(m/60)).padStart(2,'0')}:${String(m%60).padStart(2,'0')}`;
export const minutes=(s:string)=>Number(s.slice(0,2))*60+Number(s.slice(3));
export function dayPlanLegs(t:Trip,day:number,stops:string[]){const start=cityAt(t,day===1?1:day-1).id,end=cityAt(t,day).id;const route=[start,...stops,end].filter((c,i,a)=>!i||c!==a[i-1]);return route.slice(1).map((to,i)=>({from:route[i],to,options:journeyOptions(cityById(route[i]),cityById(to))}));}
export function buildDayPlan(t:Trip,day:number,stops:string[],modes:string[],start:string):Trip{if(!Number.isInteger(day)||day<1||day>t.days||stops.length<1||stops.length>5||stops.some(x=>!cityById(x))||new Set(stops).size!==stops.length)throw Error('Pilih 1–5 kota berbeda pada hari yang valid.');if(!/^\d{2}:\d{2}$/.test(start)||minutes(start)<360||minutes(start)>1200)throw Error('Mulai antara 06.00 dan 20.00.');if(t.items.some(x=>x.day===day&&x.paid&&['Wisata','Makan','Transportasi'].includes(x.category)))throw Error('Ada aktivitas atau transportasi dibayar pada hari ini. Sesuaikan booking terlebih dahulu.');let now=minutes(start);if(day===1&&t.flight&&now<minutes(t.flight.arrive)+120+(t.flight.arrivalDay||0)*1440)throw Error('Mulai minimal 2 jam setelah penerbangan tiba.');const ret=t.items.find(x=>x.returnLeg&&x.day===day),deadline=ret?minutes(ret.time)-180:t.journey!=='oneway'&&day===t.days&&t.flight?minutes(t.flight.returnDepart)-180:1320;const legs=dayPlanLegs(t,day,stops),items:Item[]=t.items.filter(x=>x.day!==day||!['Wisata','Makan','Transportasi'].includes(x.category)||['transport-local','city-local','transport-airport','city-return','city-transfer-1'].includes(x.id));let current=cityAt(t,day===1?1:day-1).id,index=0;
 const move=(to:string)=>{if(current===to)return;const leg=legs[index],opt=leg.options.find(o=>o.id===modes[index])||leg.options[0];items.push({id:`plan-${day}-transfer-${index}`,dayPlan:true,fromCity:current,toCity:to,cityId:to,mode:opt.id,minutes:opt.minutes,title:`${cityById(current).name} → ${cityById(to).name}`,category:'Transportasi',price:opt.price,paid:false,day,time:clock(now),note:`${opt.name} · ± ${opt.minutes} menit · simulasi, termasuk akses terminal / bandara. ${opt.detail}`,generated:true});now+=opt.minutes;current=to;index++;};
 stops.forEach((id,i)=>{move(id);const c=cityById(id);c.places.filter(p=>p.category==='Wisata').slice(0,2).forEach((p,j)=>{items.push({id:`plan-${day}-${i}-visit-${j}`,dayPlan:true,cityId:id,title:p.name,place:p.name,geo:p.geo,category:'Wisata',price:p.price,paid:false,day,time:clock(now),note:'45 menit kunjungan + 15 menit cadangan perpindahan. Periksa jam buka dan moda lokal.',generated:true});now+=60;});const p=c.places.find(p=>p.category==='Makan');if(p){items.push({id:`plan-${day}-${i}-meal`,dayPlan:true,cityId:id,title:`Makan · ${p.name}`,place:p.name,geo:p.geo,category:'Makan',price:p.price,paid:false,day,time:clock(now),note:'Anggaran simulasi; 45 menit makan dan perpindahan lokal.',generated:true});now+=45;}});move(cityAt(t,day).id);if(now>deadline)throw Error(`Rencana selesai sekitar ${clock(now)}, melewati batas ${clock(deadline)}. Kurangi kota, mulai lebih awal, pilih moda lebih cepat, atau pindahkan kunjungan ke hari lain.`);const localTransportDays=(t.localTransportDays||[]).filter(d=>d!==day);const adjusted=items.map(x=>x.reserveOriginal!==undefined?{...x,price:x.reserveOriginal*(t.days-localTransportDays.length)/t.days}:x);return {...t,localTransportDays,dayPlans:{...t.dayPlans,[String(day)]:{cities:stops,modes:legs.map((l,i)=>(l.options.find(o=>o.id===modes[i])||l.options[0]).id),start}},items:adjusted};}
