import {useEffect,useId,useRef,useState} from 'react';
import {Globe,MapPin,X,Loader2} from 'lucide-react';
type Location={code:string;city:string;name:string;country:string};
export default function DestinationInput({onChange}:{onChange:(code:string)=>void}){
 const [text,setText]=useState(''),[options,setOptions]=useState<Location[]>([]),[selected,setSelected]=useState(''),[error,setError]=useState(''),[open,setOpen]=useState(false),[loading,setLoading]=useState(false),[active,setActive]=useState(-1);const id=useId(),root=useRef<HTMLDivElement>(null);
 useEffect(()=>{const close=(e:PointerEvent)=>{if(!root.current?.contains(e.target as Node))setOpen(false)};document.addEventListener('pointerdown',close);return()=>document.removeEventListener('pointerdown',close)},[]);
 useEffect(()=>{setActive(-1);setOptions([]);setError('');if(text===selected||text.trim().length<2){setLoading(false);return;}const c=new AbortController();setLoading(true);const timer=setTimeout(async()=>{try{const r=await fetch('/api/locations?q='+encodeURIComponent(text),{signal:AbortSignal.any([c.signal,AbortSignal.timeout(10000)])});if(!r.ok)throw Error();const d=await r.json();setOptions(d.locations||[]);}catch{if(!c.signal.aborted)setError('Lokasi belum dapat dimuat. Coba lagi.')}finally{if(!c.signal.aborted)setLoading(false)}},250);return()=>{clearTimeout(timer);c.abort()}},[text,selected]);
 function choose(o?:Location){const label=o?`${o.city} (${o.code})`:'';setText(label);setSelected(label);setOptions([]);setOpen(false);setError('');onChange(o?.code||'all')}
 return <div className="destination-picker" ref={root}><div className="destination-field"><Globe size={19}/><input role="combobox" aria-label="Kota, negara, atau bandara tujuan" aria-autocomplete="list" aria-expanded={open} aria-controls={id} aria-activedescendant={active>=0?`${id}-${active}`:undefined} placeholder="Ke mana saja" value={text} onFocus={()=>setOpen(true)} onChange={e=>{setText(e.target.value);setSelected('');setOpen(true);onChange(e.target.value.trim()?'invalid':'all')}} onKeyDown={e=>{if(e.key==='Escape')setOpen(false);if(e.key==='ArrowDown'){e.preventDefault();setOpen(true);setActive(Math.min(active+1,options.length-1))}if(e.key==='ArrowUp'){e.preventDefault();setActive(Math.max(0,active-1))}if(e.key==='Enter'&&open&&active>=0){e.preventDefault();choose(options[active])}}}/>{text&&<button type="button" aria-label="Hapus tujuan" onClick={()=>choose()}><X size={17}/></button>}</div>{open&&<div className="location-options" id={id} role="listbox" aria-label="Pilihan tujuan"><button type="button" role="option" aria-selected={!text} onClick={()=>choose()}><Globe size={19}/><span><strong>Ke mana saja</strong><small>Temukan destinasi dengan tiket murah</small></span></button>{loading&&<p role="status"><Loader2 size={15}/> Mencari tujuan…</p>}{options.map((o,i)=><button type="button" role="option" aria-selected={i===active} id={`${id}-${i}`} key={o.code} onClick={()=>choose(o)}><MapPin size={18}/><span><strong>{o.city}<b>{o.code}</b></strong><small>{o.country} · {o.name}</small></span></button>)}{!loading&&text!==selected&&text.length>=2&&!options.length&&!error&&<p>Tidak ada hasil. Coba nama kota atau kode bandara.</p>}{!text&&<p>Ketik kota, negara, atau kode bandara. Pilih hasil untuk menentukan tujuan.</p>}{error&&<p role="alert">{error}</p>}</div>}</div>
}
