import TransportBooking from './transport-booking';
'use client';
import {useState} from 'react';
import HotelPhoto,{HotelPhotoCredits} from './hotel-photo';
import {Plane,Hotel,TrainFront,Search} from 'lucide-react';
import FlightSearch,{Choice,FlightTimes} from './flight-search';
import ProviderCompare from './provider-compare';
import {destinations,Trip,addDays,dayDiff,flightOptions,makeTrip,money} from './travel-data';
import {providerPrices} from './provider-data';
import {cities,cityById} from './cities';
import {hotelCatalog,hotelPlatforms} from './hotel-planner';
import {journeyOptions} from './transport-data';
const today=()=>new Date().toISOString().slice(0,10);
export default function DirectSearch(props:{kind:'flights'|'hotels'|'transport';onChoose:(t:Trip)=>void}){return props.kind==='flights'?<FlightSearch direct onChoose={props.onChoose}/>:<FixedSearch {...props}/>}
function FixedSearch({kind,onChoose}:{kind:'flights'|'hotels'|'transport';onChoose:(t:Trip)=>void}){
 const [from,setFrom]=useState(kind==='flights'?'CGK':'kl'),[to,setTo]=useState(kind==='transport'?'melaka':'kl'),[start,setStart]=useState(addDays(today(),30)),[end,setEnd]=useState(addDays(today(),33)),[people,setPeople]=useState('1'),[journey,setJourney]=useState('return'),[mode,setMode]=useState('all'),[sort,setSort]=useState('price'),[airline,setAirline]=useState('all'),[stars,setStars]=useState('all'),[name,setName]=useState(''),[min,setMin]=useState('0'),[max,setMax]=useState('3000000'),[expanded,setExpanded]=useState(''),[error,setError]=useState('');
 const [q,setQ]=useState<null|{from:string;to:string;start:string;end:string;people:number;journey:string;mode:string}>(null);
 const title=kind==='flights'?'Cari tiket pesawat':kind==='hotels'?'Cari hotel':'Cari transportasi';const Icon=kind==='flights'?Plane:kind==='hotels'?Hotel:TrainFront;
 function search(e:React.FormEvent){e.preventDefault();if(start<today()){setError('Pilih tanggal hari ini atau setelahnya.');return}if((kind==='hotels'||kind==='flights'&&journey==='return')&&(end<=start||dayDiff(start,end)>30)){setError('Tanggal akhir harus setelah tanggal awal, maksimal 30 hari.');return}if(kind==='transport'&&from===to){setError('Pilih kota asal dan tujuan yang berbeda.');return}setQ({from,to,start,end,people:+people,journey,mode});setExpanded('');setAirline('all');setError('')}
 const d=destinations.find(d=>d.id===q?.to);const flights=q&&d?flightOptions(d,q.from,q.start,q.end,q.journey==='oneway').filter(f=>airline==='all'||f.airline===airline).sort((a,b)=>sort==='duration'?a.duration-b.duration:providerPrices(a,q.start)[0].total-providerPrices(b,q.start)[0].total):[];
 const hotels=q?hotelCatalog(q.to).filter(h=>h.name.toLowerCase().includes(name.toLowerCase())&&(stars==='all'||h.stars===+stars)&&h.night>=+min&&h.night<=+max).sort((a,b)=>sort==='stars'?b.stars-a.stars:sort==='rating'?b.rating-a.rating:a.night-b.night):[];
 const stay:Trip|undefined=q?{destination:q.to,origin:'CGK',start:q.start,days:dayDiff(q.start,q.end)+1,people:q.people,budget:0,items:[]}:undefined;
 const rides=q&&kind==='transport'?journeyOptions(cityById(q.from),cityById(q.to)).filter(r=>q.mode==='all'||r.id===q.mode).sort((a,b)=>sort==='duration'?a.minutes-b.minutes:sort==='best'?a.score-b.score:a.price-b.price):[];
 return <section className="direct-search"><div className="direct-heading"><span className="strip-icon"><Icon size={26}/></span><div><div className="eyebrow">CARI & PESAN</div><h1>{title}</h1><p>Bandingkan pilihan, lalu pesan di penyedia. Tidak perlu membuat itinerary atau masuk akun sortTrip.</p></div></div><form className="direct-form" onSubmit={search}>
 {kind==='flights'&&<label>Jenis perjalanan<Choice label="Jenis tiket" value={journey} onChange={setJourney} options={[["return","Pulang-pergi"],["oneway","Sekali jalan"]]}/></label>}
 {kind!=='hotels'&&<label>Dari<Choice label="Asal perjalanan" value={from} onChange={setFrom} options={kind==='flights'?[["CGK","Jakarta (CGK)"],["SUB","Surabaya (SUB)"],["DPS","Denpasar (DPS)"]]:cities.map(c=>[c.id,c.name+' · '+c.country])}/></label>}
 <label>{kind==='hotels'?'Kota menginap':'Tujuan'}<Choice label="Kota tujuan" value={to} onChange={setTo} options={kind==='flights'?destinations.map(d=>[d.id,d.city+' ('+d.code+')']):cities.map(c=>[c.id,c.name+' · '+c.country])}/></label>
 <label>{kind==='hotels'?'Check-in':'Tanggal berangkat'}<input type="date" min={today()} required value={start} onChange={e=>setStart(e.target.value)}/></label>{(kind==='hotels'||kind==='flights'&&journey==='return')&&<label>{kind==='hotels'?'Check-out':'Tanggal pulang'}<input type="date" min={addDays(start||today(),1)} required value={end} onChange={e=>setEnd(e.target.value)}/></label>}
 <label>{kind==='hotels'?'Tamu dewasa':'Penumpang dewasa'}<Choice label="Jumlah orang" value={people} onChange={setPeople} options={[1,2,3,4,5,6,7,8].map(n=>[String(n),n+' orang'])}/></label>
 {kind==='transport'&&<label>Moda<Choice label="Jenis transportasi" value={mode} onChange={setMode} options={[["all","Semua moda"],["train","Kereta / train"],["bus","Bus"],["car","Mobil / taksi"],["flight","Pesawat antarkota"],["ferry","Ferry"],["airport","Transfer bandara"]]}/></label>}
 <button className="primary" type="submit"><Search size={18}/> Cari {kind==='hotels'?'hotel':kind==='flights'?'tiket':'transportasi'}</button>{error&&<p className="search-error" role="alert">{error}</p>}</form>
 {!q?<div className="search-welcome"><Icon size={25}/><p>Pilih tujuan dan tanggal untuk melihat perbandingan contoh. Katalog awal mencakup Malaysia, Thailand, dan Singapura.</p></div>:<div className="direct-results"><div className="section-heading"><div><h2>{kind==='hotels'?'Penginapan di '+cityById(q.to).name:kind==='flights'?'Pilihan penerbangan':'Pilihan perjalanan'}</h2><p>{q.start}{kind==='hotels'||kind==='flights'&&q.journey==='return'?' — '+q.end:''} · {q.people} orang · simulasi</p></div><Choice label="Urutkan hasil" value={sort} onChange={setSort} options={kind==='hotels'?[["price","Harga terendah"],["stars","Bintang tertinggi"],["rating","Rating tertinggi"]]:[["price","Termurah"],["duration","Tercepat"],...(kind==='transport'?[["best","Rekomendasi terbaik"]]:[])]}/></div>
 {kind==='flights'&&d&&<div className="flight-filters"><Choice label="Maskapai penerbangan" value={airline} onChange={setAirline} options={[["all","Semua maskapai"],...flightOptions(d,q.from,q.start,q.end,q.journey==='oneway').map(f=>[f.airline,f.airline])]}/></div>}
 {kind==='flights'&&d&&flights.map(f=>{const t=makeTrip(d,q.from,q.start,Math.min(14,Math.max(2,q.journey==='oneway'?4:dayDiff(q.start,q.end)+1)),q.people,4000000,f);/* Preserve requested return date even when planner supports a shorter range. */const directTrip={...t,days:q.journey==='oneway'?4:dayDiff(q.start,q.end)+1};const best=providerPrices(f,q.start)[0];return <div key={f.id}><button className="flight-option clickable-flight direct-flight" aria-expanded={expanded===f.id} onClick={()=>setExpanded(expanded===f.id?'':f.id)}><div className="airline"><Plane size={24}/><div><h3>{f.airline}</h3><p>{f.stops?'Transit':'Langsung'} · simulasi</p></div></div><FlightTimes f={f} origin={q.from} code={d.code}/><div className="flight-price"><strong>{money(best.total)}</strong><small>/ orang · via {best.name}</small><span>Lihat platform ▾</span></div></button>{expanded===f.id&&<ProviderCompare trip={directTrip} onChange={onChoose} allowItinerary={directTrip.days<=14}/>}</div>})}
 {kind==='hotels'&&stay&&<><div className="direct-form"><label>Nama hotel<input placeholder="Cari nama hotel" value={name} onChange={e=>setName(e.target.value)}/></label><label>Bintang<Choice label="Bintang hotel" value={stars} onChange={setStars} options={[["all","Semua bintang"],["2","2 bintang"],["3","3 bintang"],["4","4 bintang"]]}/></label><label>Min. / kamar / malam<input type="number" min="0" value={min} onChange={e=>setMin(e.target.value)}/></label><label>Maks. / kamar / malam<input type="number" min="0" value={max} onChange={e=>setMax(e.target.value)}/></label></div><p className="inline-note">Harga, bintang, dan rating adalah contoh. Estimasi {Math.ceil(q.people/2)} kamar, maksimal 2 dewasa per kamar; periksa kapasitas di penyedia.</p>{hotels.map(h=><article className="journey-leg" key={h.id}><button className="option-expander hotel-option" aria-expanded={expanded===h.id} onClick={()=>setExpanded(expanded===h.id?'':h.id)}><HotelPhoto id={h.id}/><span className="hotel-option-copy"><strong>{h.name}</strong><span>{'★'.repeat(h.stars)} · {h.rating}/10 · data contoh</span><span>Dari {money(h.night)} / kamar / malam</span><small>Lihat platform ▾</small></span></button>{expanded===h.id&&hotelPlatforms(h,stay,1,stay.days-1).map(r=><div className="provider-row" key={r.name}><div><strong>{r.name}</strong><small>{r.name==='Booking.com'?'Nama hotel, tanggal, dan tamu diteruskan.':'Halaman umum; isi detail di penyedia.'}</small></div><div><strong>{money(r.total)}</strong><small>Total {stay.days-1} malam · semua kamar</small></div><a className="secondary" target="_blank" rel="noreferrer" href={r.url}>Beli langsung ↗</a></div>)}</article>)}<HotelPhotoCredits/>{!hotels.length&&<div className="empty">Belum ada hotel sesuai filter. Coba ubah nama atau rentang harga.</div>}</>}
 {kind==='transport'&&<><p className="inline-note">Perkiraan rute dan biaya / orang, bukan jadwal atau tiket tersedia pada tanggal pilihan. Termasuk perkiraan akses terminal; koneksi kereta dan perbatasan perlu diverifikasi.</p>{rides.map(r=><article className="journey-leg" key={r.id}><h3>{r.name}</h3><p>{cityById(q.from).name} → {cityById(q.to).name}</p><div className="direct-ride-price"><strong>{money(r.price)} / orang</strong><span>± {Math.floor(r.minutes/60)} jam {r.minutes%60} menit</span></div><p>{r.detail}</p><p>Estimasi {q.people} orang: {money(r.price*q.people)}</p><a className="secondary" target="_blank" rel="noreferrer" href={`https://www.google.com/maps/dir/?api=1&origin=${encodeURIComponent(cityById(q.from).name)}&destination=${encodeURIComponent(cityById(q.to).name)}&travelmode=${r.id==='car'?'driving':'transit'}`}>Lihat rute ↗</a></article>)}{!rides.length&&<div className="empty"><h3>Belum ada pilihan dalam katalog contoh</h3><p>{q.mode==='ferry'?'Rute dan tarif ferry belum tersedia.':q.mode==='airport'?'Transfer bandara belum tersedia di pencarian langsung.':'Coba moda lain untuk rute ini.'}</p></div>}<div className="city-planner"><h3>Temukan jadwal & tiket</h3><p className="inline-note">Buka pilihan pemesanan untuk memeriksa harga aktual. Estimasi di atas bukan penawaran tiket.</p><TransportBooking from={q.from} to={q.to} date={q.start} people={q.people}/></div></>}
 </div>}</section>
}
