import {useState} from 'react';
import {addDays,type Trip} from './travel-data';
import {manualPartnerItem,applyPartnerSelection,partnerTripKey,tripLabel,type PartnerSearchProps} from './partner-selection';
export default function PartnerSelectionForm({kind,trip,trips,context,onAdd}:PartnerSearchProps&{kind:'hotels'|'transport'}){
 const [replace,setReplace]=useState(true);
 const choices=[...(trip?[trip]:[]),...trips.filter(t=>!trip?.id||t.id!==trip.id)];
 const [target,setTarget]=useState('0'),[name,setName]=useState(context?.name||''),[date,setDate]=useState(context?.date||trip?.start||''),[checkOut,setCheckOut]=useState(context?.checkOut||trip&&addDays(trip.start,Math.min(1,trip.days-1))||''),[from,setFrom]=useState(context?.from||''),[to,setTo]=useState(context?.to||(trip?tripLabel(trip):'')),[price,setPrice]=useState(''),[error,setError]=useState('');
 if(!choices.length)return <p>Buat atau buka trip terlebih dahulu untuk menyimpan pilihan mitra.</p>;
 const selected=choices[Number(target)]||choices[0];
 const previous=context?.tripKey===partnerTripKey(selected)?selected.items.find(x=>x.id===context.replaceId&&!x.paid):undefined;

 function submit(e:React.FormEvent){e.preventDefault();try{const item=manualPartnerItem(selected,kind,{name,date,checkOut,from,to,price},crypto.randomUUID());const replaceId=replace?previous?.id:undefined;applyPartnerSelection(selected,item,replaceId);onAdd(selected,item,replaceId);}catch(e){setError(e instanceof Error?e.message:'Pilihan belum dapat disimpan.');}}
 return <details className="partner-selection"><summary>Simpan pilihan ke trip</summary><p>Setelah memilih di mitra, konfirmasikan data berikut. Tidak perlu memasukkan nomor booking, data pembayaran, atau credential.</p><form onSubmit={submit}><label>Trip tujuan<select value={target} onChange={e=>{const t=choices[Number(e.target.value)];setTarget(e.target.value);setDate(t.start);setCheckOut(addDays(t.start,Math.min(1,t.days-1)));}}>{choices.map((t,i)=><option key={i} value={i}>{tripLabel(t)} · {t.start}{t===trip?' · trip terbuka':''}</option>)}</select></label><label>{kind==='hotels'?'Nama hotel pilihan':'Nama layanan / operator'}<input required maxLength={160} value={name} onChange={e=>setName(e.target.value)}/></label>{kind==='transport'&&<label>Asal<input required maxLength={160} value={from} onChange={e=>setFrom(e.target.value)}/></label>}<label>{kind==='hotels'?'Kota / area hotel':'Tujuan'}<input required maxLength={160} value={to} onChange={e=>setTo(e.target.value)}/></label><label>{kind==='hotels'?'Check-in':'Tanggal berangkat'}<input required type="date" min={selected.start} max={addDays(selected.start,selected.days-1)} value={date} onChange={e=>setDate(e.target.value)}/></label>{kind==='hotels'&&<label>Check-out<input required type="date" min={date} max={addDays(selected.start,selected.days-1)} value={checkOut} onChange={e=>setCheckOut(e.target.value)}/></label>}<label>{kind==='hotels'?'Anggaran total menginap / orang (Rp, opsional)':'Anggaran transportasi / orang (Rp, opsional)'}<input type="number" min="0" max="1000000000" value={price} onChange={e=>setPrice(e.target.value)} placeholder="Kosong jika belum diketahui"/></label>{previous&&<label><span><input type="checkbox" checked={replace} onChange={e=>setReplace(e.target.checked)}/> Ganti pilihan sebelumnya: {previous.title}</span></label>}{error&&<p role="alert">{error}</p>}<button className="primary">{replace&&previous?'Ganti pilihan di itinerary':'Tambahkan ke itinerary'}</button><small>Menambah ke draft. Simpan itinerary untuk menyimpan ke akun.</small></form></details>;
}
