import {useEffect,useState} from 'react';
import {supabase} from './supabase';
import {type Trip,money} from './travel-data';
export default function PriceWatch({trip}:{trip?:Trip|null}){
 const [email,setEmail]=useState(false),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[notices,setNotices]=useState<any[]>([]),[watches,setWatches]=useState<any[]>([]);
 async function load(){if(!supabase)return;const [n,w]=await Promise.all([supabase.from('price_notifications').select('*').order('created_at',{ascending:false}).limit(20),supabase.from('price_watches').select('id,trip_id,enabled,email_enabled,last_checked,last_status,best_price')]);if(n.error||w.error){setMessage('Price Watch belum dikonfigurasi pada database.');return;}setNotices(n.data||[]);setWatches(w.data||[]);}
 useEffect(()=>{load()},[trip?.id]);
 async function toggle(id:string,enabled:boolean,emailOn=email){if(!supabase)return;setBusy(true);setMessage('');const {error}=await supabase.rpc('set_price_watch',{p_trip_id:id,p_enabled:enabled,p_email:emailOn});setMessage(error?error.message:enabled?'Price Watch diaktifkan. Harga dicek sekitar sekali sehari selama Trip Pass aktif.':'Price Watch dimatikan.');await load();setBusy(false);}
 return <section className="ai-planner"><div className="eyebrow">PRICE WATCH · TRIP PASS</div><h2>Temukan waktu yang lebih hemat</h2><p>Pantau harga indikatif tiket untuk rute dan tanggal perjalanan tersimpan. Notifikasi muncul saat harga lebih rendah dari harga terendah yang pernah tercatat.</p>{trip&&<><label><input type="checkbox" checked={email} onChange={e=>setEmail(e.target.checked)}/> Kirim juga melalui email akun saya (memerlukan layanan email aktif).</label><p><button className="primary" disabled={busy||!trip.id} onClick={()=>trip.id&&toggle(trip.id,true)}>Aktifkan untuk perjalanan ini</button></p>{!trip.id&&<p>Simpan itinerary terlebih dahulu.</p>}</>}<p role="status">{message}</p>{watches.map(w=><div className="notice" key={w.id}><span>{w.enabled?'Pemantauan diaktifkan':'Pemantauan mati'} · Terakhir dicek: {w.last_checked?new Date(w.last_checked).toLocaleString('id-ID'):'menunggu jadwal'} · {w.last_status==='error'?'Pemeriksaan gagal':w.last_status==='no_data'?'Belum ada data harga':''}</span>{w.enabled&&<button disabled={busy} onClick={()=>toggle(w.trip_id,false,false)}>Matikan</button>}</div>)}<h3>Notifikasi harga</h3>{notices.length===0&&<p>Belum ada penurunan harga tercatat.</p>}{notices.map(n=><article className="notice" key={n.id}><div><strong>{money(n.old_price)} → {money(n.price)}</strong><p>{new Date(n.created_at).toLocaleString('id-ID')} · harga per 1 dewasa</p><a href={n.booking_url} target="_blank" rel="noopener noreferrer sponsored">Periksa penawaran</a></div></article>)}<p className="inline-note">Maskapai/jam dapat berbeda. Belum membandingkan bagasi atau ketentuan tarif. Harga API bersifat indikatif, bukan jaminan harga checkout. Pemantauan berhenti saat pass kedaluwarsa atau tanggal keberangkatan lewat. Notifikasi di akun, bukan push ke perangkat.</p></section>;
}
