'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {MapPin,Hotel,Plane,ArrowUpRight,TrainFront,Footprints,Car,Utensils} from 'lucide-react';
import {Trip,Geo,Item,destinations,geoData,money,directionsLink,shortDate,addDays} from './travel-data';
import {cityAt,hotelAt} from './cities';
import {routePoints,localLegs} from './local-transport-data';
import LocalTransport from './local-transport';
import {Choice} from './flight-search';
type Point={id:string;name:string;geo:Geo;kind:string;time:string};
function km(a:Geo,b:Geo){const r=Math.PI/180,x=(b.lat-a.lat)*r,y=(b.lng-a.lng)*r;return 6371*2*Math.atan2(Math.sqrt(Math.sin(x/2)**2+Math.cos(a.lat*r)*Math.cos(b.lat*r)*Math.sin(y/2)**2),Math.sqrt(1-(Math.sin(x/2)**2+Math.cos(a.lat*r)*Math.cos(b.lat*r)*Math.sin(y/2)**2)))}
export default function RouteMap({trip,onChange}:{trip:Trip;onChange:(t:Trip)=>void}){
 const [day,setDay]=useState('1'),[mode,setMode]=useState('transit'),[error,setError]=useState('');const container=useRef<HTMLDivElement>(null);const mapRef=useRef<any>(null);const d=destinations.find(d=>d.id===trip.destination)!,geo=geoData[d.id];
 const all=trip.items.filter(x=>x.day===+day&&['Wisata','Makan'].includes(x.category));const points:Point[]=routePoints(trip,+day);const signature=JSON.stringify(points);
 useEffect(()=>{let disposed=false;let map:any;const resize=new ResizeObserver(()=>mapRef.current?.invalidateSize());if(container.current)resize.observe(container.current);import('leaflet').then(L=>{if(disposed||!container.current)return;map=L.map(container.current,{scrollWheelZoom:false});mapRef.current=map;L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>',maxZoom:19}).on('tileerror',()=>setError('Latar peta belum termuat. Titik dan tautan Google Maps tetap tersedia.')).addTo(map);const bounds: [number,number][]=[];points.forEach((p,i)=>{bounds.push([p.geo.lat,p.geo.lng]);const color=p.kind==='Penginapan'?'#176b53':p.kind==='Makan'?'#bd6b30':p.kind==='Bandara'?'#4b6479':'#326fe5';const icon=L.divIcon({className:'route-marker',html:`<span style="background:${color}">${i+1}</span>`,iconSize:[30,36],iconAnchor:[15,32]});const label=document.createElement('span');label.textContent=`${i+1}. ${p.name}`;L.marker([p.geo.lat,p.geo.lng],{icon,title:p.name}).addTo(map).bindPopup(label)});if(bounds.length){L.polyline(bounds,{color:'#3679de',weight:3,dashArray:'7 9',opacity:.8}).addTo(map);map.fitBounds(bounds,{padding:[35,35],maxZoom:15})}else map.setView([geo.hotel.geo.lat,geo.hotel.geo.lng],13)}).catch(()=>setError('Peta belum tersedia. Buka rute di Google Maps di bawah.'));return()=>{disposed=true;resize.disconnect();map?.remove();mapRef.current=null}},[signature]);
 return <section className="route-section"><div className="map-toolbar"><Choice label="Hari pada peta" value={day} onChange={setDay} options={Array.from({length:trip.days},(_,i)=>[String(i+1),`Hari ${i+1} · ${shortDate(addDays(trip.start,i))}`])}/></div><div className="map-canvas" ref={container} role="region" aria-label={`Peta titik perjalanan ${cityAt(trip,+day).name} hari ${day}`}/><div className="map-legend"><span><i style={{background:'#176b53'}}/>Penginapan</span><span><i style={{background:'#326fe5'}}/>Wisata</span><span><i style={{background:'#bd6b30'}}/>Makan</span><span><i style={{background:'#4b6479'}}/>Bandara</span></div>{error&&<p role="status" className="inline-note">{error}</p>}<p className="inline-note">Garis putus-putus menunjukkan urutan titik, bukan jalur jalan. Posisi perkiraan. Durasi dan biaya dihitung kasar dari jarak, belum dari jadwal angkutan atau tarif Grab. Pilih moda per perpindahan di bawah untuk memasukkan estimasinya ke anggaran. Transfer bandara tetap pada itinerary.</p>{all.some(x=>!x.geo)&&<p className="inline-note">{all.filter(x=>!x.geo).length} item tanpa koordinat belum ditampilkan. Isi koordinat melalui Edit aktivitas.</p>}<LocalTransport key={day+signature} trip={trip} day={+day} onChange={onChange}/></section>
}
