export type Geo={lat:number;lng:number};
export type Item={routeKey?:string;reserveOriginal?:number;dayPlan?:boolean;fromCity?:string;toCity?:string;mode?:string;minutes?:number;returnLeg?:boolean;fromCode?:string;toCode?:string;travelDate?:string;hotelId?:string;provider?:string;cityId?:string;generated?:boolean;id:string;title:string;category:string;price:number;paid:boolean;day:number;time:string;note:string;shared?:boolean;geo?:Geo;place?:string;bookingUrl?:string;checkin?:string;checkout?:string};
export type Flight={oneWay?:boolean;id:string;airline:string;price:number;depart:string;arrive:string;returnDepart:string;returnArrive:string;duration:number;stops:number;via?:string;arrivalDay:number;returnArrivalDay:number};
export type Trip={dayPlans?:Record<string,{cities:string[];modes:string[];start:string}>;localTransportDays?:number[];journey?:"return"|"oneway";cityDays?:string[];id?:string;destination:string;origin:string;start:string;days:number;people:number;budget:number;items:Item[];flight?:Flight;version?:number};
export const destinations=[
{id:'kl',city:'Kuala Lumpur',country:'Malaysia',code:'KUL',image:'/kuala-lumpur.jpg',tag:'Mulai dari sini',flight:890000,night:540000,food:110000,transport:230000,description:'Langit kota, kuliner lokal, dan langkah pertama ke luar negeri.',places:['KLCC Park','Pasar Seni','Dataran Merdeka','Bukit Bintang'],duration:'2j 10m',airline:'AirAsia',offset:8,minutes:130},
{id:'bkk',city:'Bangkok',country:'Thailand',code:'DMK',image:'/bangkok.jpg',tag:'Untuk pencinta kuliner',flight:1450000,night:460000,food:130000,transport:310000,description:'Menyusuri sungai, menjelajah kuil, mencicipi rasa baru.',places:['Wat Arun','Wat Pho','Lumphini Park','Phra Sumen Fort'],duration:'3j 30m',airline:'Thai Lion Air',offset:7,minutes:210},
{id:'sin',city:'Singapura',country:'Singapura',code:'SIN',image:'/singapore.jpg',tag:'Kota mudah dijelajahi',flight:1150000,night:650000,food:220000,transport:300000,description:'Jalan kaki di tepi teluk dan keliling kota dengan MRT.',places:['Merlion Park','Kampong Glam','Gardens by the Bay (area luar)','Chinatown'],duration:'1j 50m',airline:'Scoot',offset:8,minutes:110}];
export const geoData:Record<string,{airport:Geo;hotel:{name:string;geo:Geo;url:string;shared:boolean};visits:Geo[];meals:{name:string;geo:Geo;price:number;menu:string}[]}>= {
 kl:{airport:{lat:2.7456,lng:101.7072},hotel:{name:'Travelodge Kuala Lumpur City Centre',geo:{lat:3.1448,lng:101.6951},url:'https://www.booking.com/hotel/my/travelodge-city-centre.html',shared:true},visits:[{lat:3.1557,lng:101.7156},{lat:3.1453,lng:101.6953},{lat:3.1486,lng:101.6934},{lat:3.1465,lng:101.7114}],meals:[{name:'Central Market Food Court',geo:{lat:3.1453,lng:101.6953},price:35000,menu:'Sarapan sederhana + minum'},{name:'Central Market Food Court',geo:{lat:3.1453,lng:101.6953},price:45000,menu:'Nasi / mi + minum'},{name:'Jalan Alor Food Street',geo:{lat:3.1457,lng:101.7084},price:55000,menu:'Makan malam di gerai pilihan'}]},
 bkk:{airport:{lat:13.9126,lng:100.6068},hotel:{name:'Rambuttri Village Plaza',geo:{lat:13.7616,lng:100.4976},url:'https://www.booking.com/hotel/th/rambuttri-village-plaza.html',shared:true},visits:[{lat:13.7437,lng:100.4889},{lat:13.7465,lng:100.493},{lat:13.7308,lng:100.5418},{lat:13.7634,lng:100.4964}],meals:[{name:'Wang Lang Market',geo:{lat:13.7565,lng:100.4858},price:35000,menu:'Sarapan + minum'},{name:'Tha Maharaj',geo:{lat:13.7555,lng:100.4884},price:55000,menu:'Makan siang di area kuliner'},{name:'Wang Lang Market',geo:{lat:13.7565,lng:100.4858},price:50000,menu:'Makan malam; cek jam gerai'}]},
 sin:{airport:{lat:1.3644,lng:103.9915},hotel:{name:'CUBE Boutique Capsule Hotel at Kampong Glam',geo:{lat:1.3025,lng:103.8592},url:'https://www.booking.com/hotel/sg/cube-kampong-glam.html',shared:false},visits:[{lat:1.2868,lng:103.8545},{lat:1.302,lng:103.859},{lat:1.2816,lng:103.8636},{lat:1.2838,lng:103.8435}],meals:[{name:'Maxwell Food Centre',geo:{lat:1.2804,lng:103.8447},price:60000,menu:'Sarapan + minum'},{name:'Maxwell Food Centre',geo:{lat:1.2804,lng:103.8447},price:90000,menu:'Nasi / mi + minum'},{name:'Amoy Street Food Centre',geo:{lat:1.2792,lng:103.8467},price:95000,menu:'Makan malam; cek gerai yang buka'}]}
};
export const money=(n:number)=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(n);
export const addDays=(iso:string,n:number)=>{const d=new Date(iso+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10)};
export const dayDiff=(a:string,b:string)=>Math.round((Date.parse(b+'T12:00:00Z')-Date.parse(a+'T12:00:00Z'))/86400000);
export const shortDate=(iso:string)=>new Date(iso+'T12:00:00Z').toLocaleDateString('id-ID',{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'});
export function validDate(v:string){return /^\d{4}-\d{2}-\d{2}$/.test(v)&&Number.isFinite(Date.parse(v+'T12:00:00Z'))&&new Date(v+'T12:00:00Z').toISOString().slice(0,10)===v;}
function clock(min:number){return `${String(Math.floor(((min%1440)+1440)%1440/60)).padStart(2,'0')}:${String(((min%60)+60)%60).padStart(2,'0')}`}
export function flightOptions(d:typeof destinations[number],origin:string,start:string,end:string,oneWay=false):Flight[]{const shift=origin==='DPS'?8:7;const extra=origin==='DPS'?60:origin==='SUB'?30:0;const day=Date.parse(start)/86400000;const factor=((day%7)+7)%7*25000+(oneWay?0:(Date.parse(end)/86400000%5)*15000);return [0,1,2].map(i=>{const duration=d.minutes+extra+(i===2?140:i===1?-5:0);const dep=[420,625,780][i];const ret=[1080,1160,990][i];const am=dep+duration+(d.offset-shift)*60,rm=ret+duration+(shift-d.offset)*60;return{oneWay,id:`${oneWay?"ow":"rt"}-${d.id}-${origin}-${start}-${oneWay?"":end}-${i}`,airline:i===0?d.airline:i===1?(d.id==='kl'?'Batik Air':d.id==='sin'?'Citilink':'Thai AirAsia'):'Contoh maskapai transit',price:(oneWay?Math.round(d.flight*.58):d.flight)+(origin==='DPS'?350000:origin==='SUB'?180000:0)+factor+[0,220000,350000][i],depart:clock(dep),arrive:clock(am),returnDepart:clock(ret),returnArrive:clock(rm),duration,stops:i===2?1:0,via:i===2?'KUL':undefined,arrivalDay:Math.floor(am/1440),returnArrivalDay:Math.floor(rm/1440)}})}
export type SearchCriteria={journey?:"return"|"oneway";anytime?:boolean;origin:string;destination:string;outFrom:string;outTo:string;backFrom:string;backTo:string;minDays:number;maxDays:number;people:number;budget:number};
export type DateOption={start:string;end:string;days:number;flight:Flight;total:number};
export function resolveSearchDates(q:SearchCriteria,today=new Date().toISOString().slice(0,10)):SearchCriteria {
 const anytime=![q.outFrom,q.outTo,q.backFrom,q.backTo].some(Boolean);
 const tomorrow=addDays(today,1);
 const outFrom=q.outFrom||(q.backFrom?([tomorrow,addDays(q.backFrom,-q.maxDays+1)].sort().at(-1)!):tomorrow);
 const outTo=q.outTo||(q.outFrom?q.outFrom:q.backTo?addDays(q.backTo,-q.minDays+1):q.backFrom?addDays(q.backFrom,-q.minDays+1):addDays(outFrom,179));
 const backFrom=q.backFrom||addDays(outFrom,q.minDays-1);
 const backTo=q.backTo||(q.backFrom?q.backFrom:addDays(outTo,q.maxDays-1));
 return {...q,outFrom,outTo,backFrom,backTo,anytime};
}
export function dateOptions(d:typeof destinations[number],q:SearchCriteria):DateOption[]{const out:DateOption[]=[];if(![q.outFrom,q.outTo,q.backFrom,q.backTo].every(validDate)||dayDiff(q.outFrom,q.outTo)>366||dayDiff(q.backFrom,q.backTo)>380||q.minDays<2||q.maxDays>14||q.minDays>q.maxDays)return out;for(let a=q.outFrom;a<=q.outTo;a=addDays(a,1)){for(let days=q.minDays;days<=q.maxDays;days++){const b=addDays(a,days-1);if(b<q.backFrom||b>q.backTo)continue;const flight=flightOptions(d,q.origin,a,b,q.journey==='oneway')[0];const t=makeTrip(d,q.origin,a,days,q.people,q.budget,flight);out.push({start:a,end:b,days,flight,total:costs(t).perPerson})}}return out.sort((a,b)=>a.flight.price-b.flight.price||a.total-b.total||a.start.localeCompare(b.start))}

export function makeTrip(d:typeof destinations[number],origin:string,start:string,days:number,people:number,budget:number,chosen?:Flight):Trip{const geo=geoData[d.id],end=addDays(start,days-1),flight=chosen||flightOptions(d,origin,start,end)[0];const items:Item[]=[{id:'flight',title:`${origin} → ${d.code} · ${flight.oneWay?"sekali jalan":"pulang-pergi"}`,category:'Pesawat',price:flight.price,paid:false,day:1,time:flight.depart,note:`${flight.airline} · jadwal & harga simulasi. Bagasi tambahan belum termasuk.`},{id:'hotel',title:geo.hotel.name,place:geo.hotel.name,geo:geo.hotel.geo,bookingUrl:geo.hotel.url,category:'Penginapan',price:d.night*(days-1)*(geo.hotel.shared?Math.ceil(people/2):1),shared:geo.hotel.shared,paid:false,day:1,time:Number(flight.arrive.slice(0,2))>=13?clock(Number(flight.arrive.slice(0,2))*60+Number(flight.arrive.slice(3))+120):'15:00',checkin:start,checkout:end,note:`${days-1} malam · ${geo.hotel.shared?`${Math.ceil(people/2)} kamar, maks. 2 orang/kamar`:'kapsul per orang'} · anggaran contoh, bukan tarif properti`},{id:'transport-airport',title:flight.oneWay?'Bandara → penginapan':'Bandara ↔ penginapan',category:'Transportasi',price:flight.oneWay?Math.round(d.transport/2):d.transport,paid:false,day:1,time:'',note:flight.oneWay?'Transfer kedatangan saja; estimasi.':'Cadangan transfer pulang-pergi per orang; estimasi.'},{id:'transport-local',title:'Transportasi dalam kota',category:'Transportasi',price:Math.max(1,days-1)*30000,paid:false,day:1,time:'',note:'Cadangan per hari; rincian rute ada di tab Peta & rute, sudah termasuk di sini.'}];const count=days===2?2:Math.min(4,days*2);for(let i=0;i<count;i++){const late=Number(flight.arrive.slice(0,2))>=13;const day=late?Math.min(days,2+Math.floor(i/2)):(days===2?(i===0?1:2):i===0?1:Math.min(days-1,2+Math.floor((i-1)/2)));items.push({id:`visit-${i}`,title:d.places[i],place:d.places[i],geo:geo.visits[i],category:'Wisata',price:d.id==='bkk'&&i<2?(i===0?100000:150000):0,paid:false,day,time:late?(i%2===0?'09:00':'11:00'):(i===0?'16:00':i%2===1?'09:00':'14:00'),note:'Rekomendasi dapat diedit. Biaya adalah anggaran contoh; cek tarif dan jam buka resmi.'})}for(let day=1;day<=days;day++){for(let meal=0;meal<3;meal++){const mt=[480,750,1110][meal];const arrival=Number(flight.arrive.slice(0,2))*60+Number(flight.arrive.slice(3));const departure=Number(flight.returnDepart.slice(0,2))*60+Number(flight.returnDepart.slice(3));if(day===1&&mt<arrival+120)continue;if(!flight.oneWay&&day===days&&mt>departure-180)continue;const m=geo.meals[meal];items.push({id:`meal-${day}-${meal}`,title:`${['Sarapan','Makan siang','Makan malam'][meal]} · ${m.name}`,place:m.name,geo:m.geo,category:'Makan',price:m.price,paid:false,day,time:['08:00','12:30','18:30'][meal],note:`${m.menu}. Anggaran per orang, bukan harga menu aktual. Sesuaikan jam penerbangan dan jam buka.`})}}return{journey:flight.oneWay?"oneway":"return",destination:d.id,origin,start,days,people,budget,items,flight,version:2}}
export function costs(t:Trip){let total=0,paid=0;t.items.forEach(x=>{const v=x.price*(x.shared?1:t.people);total+=v;if(x.paid)paid+=v;});return{total,paid,remaining:total-paid,perPerson:total/t.people};}
export function flightSearchUrl(from:string,to:string,date:string,people:number,end?:string){const fmt=(s:string)=>{const [y,m,d]=s.split('-');return `${+d}-${+m}-${y}`};const p=new URLSearchParams({ap:`${from}.${to}`,dt:`${fmt(date)}.${end?fmt(end):''}`,ps:`${people}.0.0`,sc:'ECONOMY'});return `https://www.traveloka.com/id-id/flight/${end?'fulltwosearch':'fullsearch'}?${p}`}
export function flightBookingUrl(t:Trip){return flightSearchUrl(t.origin,destinations.find(x=>x.id===t.destination)!.code,t.start,t.people,t.journey==='oneway'?undefined:addDays(t.start,t.days-1))}
export function hotelBookingUrl(t:Trip,item:Item){if(!item.bookingUrl?.startsWith('https://www.booking.com/hotel/')&&!item.bookingUrl?.startsWith('https://www.booking.com/searchresults.html'))return null;const u=new URL(item.bookingUrl!);u.searchParams.set('checkin',item.checkin||t.start);u.searchParams.set('checkout',item.checkout||addDays(t.start,t.days-1));u.searchParams.set('group_adults',String(t.people));u.searchParams.set('group_children','0');u.searchParams.set('no_rooms',String(item.shared?Math.ceil(t.people/2):1));u.searchParams.set('selected_currency','IDR');return u.toString()}
export function mapLink(place:string,city:string){return `https://www.google.com/maps/search/?${new URLSearchParams({api:'1',query:place+' '+city})}`}
export function directionsLink(a:string,b:string,mode:string){return `https://www.google.com/maps/dir/?${new URLSearchParams({api:'1',origin:a,destination:b,travelmode:mode})}`}
