import {useEffect,useState} from 'react';
import {supabase} from './supabase';
import type {Trip} from './travel-data';
type Status={mode:string;ownerTest:boolean;checkoutEnabled:boolean;status:string;pass:null|{expiresAt:string;remaining:number;test:boolean}};
export default function TripPass({trip,onLogin}:{trip:Trip;onLogin:()=>void}){
 const [status,setStatus]=useState<Status|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function call(action:string,refresh=false){const {data}=await supabase!.auth.getSession();if(!data.session){onLogin();return null;}const r=await fetch('/api/payments/'+action,{method:'POST',headers:{Authorization:`Bearer ${data.session.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({tripId:trip.id,refresh})});const b=await r.json();if(!r.ok)throw Error(b.error||'Permintaan gagal.');return b;}
 useEffect(()=>{let live=true;setStatus(null);setMessage('');if(trip.id&&supabase)supabase.auth.getSession().then(async({data})=>{if(!data.session)return;try{const r=await fetch('/api/payments/status',{method:'POST',headers:{Authorization:`Bearer ${data.session.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({tripId:trip.id})});const b=await r.json();if(live&&r.ok)setStatus(b);}catch{}});return()=>{live=false}},[trip.id,trip.start,trip.destination]);
 async function act(action:string){if(!supabase){setMessage('Koneksi akun belum tersedia.');return;}setBusy(true);setMessage('');try{const b=await call(action,true);if(!b)return;if(action==='checkout'){window.location.assign(b.checkoutUrl);return;}if(action==='status')setStatus(b);else {setMessage(b.message);const s=await call('status');if(s)setStatus(s);}}catch(e){setMessage(e instanceof Error?e.message:'Permintaan gagal.')}finally{setBusy(false)}}
 return <div className="trip-pass"><strong>Trip Pass · Rp15.000 / perjalanan</strong><p>30 hari masa planning · 20 permintaan AI · revisi dan alternatif melalui preferensi · Price Watch harian dan notifikasi akun. Email mengikuti ketersediaan layanan pengiriman. Tanpa perpanjangan otomatis.</p><p className="inline-note">Harga hotel/tiket wisata tetap menunggu API mitra. AI menggunakan model yang sama, dengan kuota lebih besar. Mengubah kota awal atau tanggal keberangkatan dianggap perjalanan berbeda.</p>{status?.pass?<div className="notice"><span>{status.pass.test?'Akses uji aktif':'Trip Pass aktif'} · sampai {new Date(status.pass.expiresAt).toLocaleDateString('id-ID')} · sisa {status.pass.remaining} permintaan</span></div>:<p>{status?.mode==='sandbox'?'Mode uji · jangan gunakan uang sungguhan.':'Pembayaran tersedia setelah konfigurasi dan verifikasi pengelola.'}</p>}{!trip.id&&<p>Simpan itinerary terlebih dahulu untuk memilih perjalanan yang mendapat Trip Pass.</p>}<div className="ai-controls">{!status?.pass&&<button className="primary" disabled={busy||!trip.id||!status?.checkoutEnabled} onClick={()=>act('checkout')}>{status?.mode==='sandbox'?'Uji pembayaran Midtrans':'Beli Trip Pass · Rp15.000'}</button>}{trip.id&&<button className="secondary" disabled={busy} onClick={()=>act('status')}>Cek akses / status pembayaran</button>}{status?.ownerTest&&!status.pass&&<button className="secondary" disabled={busy} onClick={()=>act('owner-test')}>Aktifkan akses uji pemilik</button>}</div>{message&&<p role="status">{message}</p>}<p className="inline-note">Jika selesai di halaman pembayaran, kembali ke perjalanan ini dan klik Cek akses. Akses diberikan setelah verifikasi server.</p></div>;
}
