import {useState} from 'react';
import {Bookmark,Plus,Trash2} from 'lucide-react';
import {type Trip,type Item,money,addDays,costs,shortDate} from './travel-data';
import {FlightTimes} from './flight-search';
export default function WorldPlanner({trip,onChange,onSave,busy,dirty}:{trip:Trip;onChange:(t:Trip)=>void;onSave:()=>void;busy:boolean;dirty:boolean}){
 const [title,setTitle]=useState(''),[category,setCategory]=useState('Wisata'),[day,setDay]=useState(1),[price,setPrice]=useState(''),[time,setTime]=useState('10:00');
 const meta=trip.destinationMeta,total=costs(trip);
 function update(id:string,values:Partial<Item>){onChange({...trip,items:trip.items.map(x=>x.id===id?{...x,...values}:x)});}
 function add(e:React.FormEvent){e.preventDefault();if(!title.trim()||!Number.isFinite(Number(price))||Number(price)<0)return;onChange({...trip,items:[...trip.items,{id:crypto.randomUUID(),title:title.trim(),category,day,price:Number(price),time,paid:false,note:'Anggaran yang dimasukkan pengguna; per orang.'}]});setTitle('');setPrice('');}
 return <><div className="planner-title"><div><div className="eyebrow">MULAI DARI TIKET, LENGKAPI BERTAHAP</div><h1>{meta?.city||trip.destination}</h1><p>{meta?.country} · {shortDate(trip.start)} – {shortDate(addDays(trip.start,trip.days-1))} · {trip.people} orang</p><p>{dirty?'Belum disimpan':'Tersimpan'}</p></div><button className="primary" disabled={busy} onClick={onSave}><Bookmark size={18}/>{busy?'Menyimpan…':'Simpan itinerary'}</button></div>
 <p className="city-warning">Rekomendasi hotel, makan, transportasi, dan wisata untuk tujuan ini belum tersedia. Subtotal hanya menghitung item yang sudah tercatat, bukan estimasi seluruh liburan. Harga tiket tersimpan tidak diperbarui otomatis.</p>
 <div className="planner-layout"><div>{trip.flight&&<section className="selected-flight"><FlightTimes f={trip.flight} origin={trip.origin} code={meta?.code||trip.destination}/><a className="primary" href={trip.flight.bookingUrl} target="_blank" rel="noopener noreferrer sponsored">Lihat penawaran</a><p>Tautan untuk 1 dewasa. Periksa jumlah penumpang dan harga akhir di penyedia.</p></section>}
 <section className="day"><h2>Lengkapi itinerary</h2><p>Tambahkan tujuan wisata, tempat makan, penginapan, atau transportasi beserta anggaran per orang.</p><form className="world-item-form" onSubmit={add}><label>Hari<select aria-label="Hari aktivitas" value={day} onChange={e=>setDay(+e.target.value)}>{Array.from({length:trip.days},(_,i)=><option value={i+1} key={i}>Hari {i+1} · {shortDate(addDays(trip.start,i))}</option>)}</select></label><label>Kategori<select value={category} onChange={e=>setCategory(e.target.value)}>{['Wisata','Makan','Penginapan','Transportasi','Pesawat'].map(c=><option key={c}>{c}</option>)}</select></label><label>Nama tempat / aktivitas<input required maxLength={160} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Jam<input type="time" required value={time} onChange={e=>setTime(e.target.value)}/></label><label>Anggaran / orang (Rp)<input type="number" min="0" max="1000000000" required value={price} onChange={e=>setPrice(e.target.value)}/></label><button className="primary"><Plus size={16}/>Tambah</button></form></section>
 {Array.from({length:trip.days},(_,i)=>i+1).map(d=><section className="day" key={d}><h3>Hari {d} · {shortDate(addDays(trip.start,d-1))}</h3>{trip.items.filter(x=>x.day===d).map(item=><article className="world-item" key={item.id}><div><strong>{item.time} · {item.title}</strong><p>{item.category} · {item.paid?'Sudah dipesan · catatan pengguna':'Belum dipesan'}</p></div><label>Biaya / orang<input aria-label={'Biaya '+item.title} type="number" min="0" max="1000000000" value={item.price} onChange={e=>{const n=Number(e.target.value);if(Number.isFinite(n)&&n>=0)update(item.id,{price:n});}}/></label><label><input type="checkbox" checked={item.paid} onChange={e=>update(item.id,{paid:e.target.checked})}/> Sudah dipesan</label>{item.id!=='flight'&&<button className="icon-button" aria-label={'Hapus '+item.title} onClick={()=>onChange({...trip,items:trip.items.filter(x=>x.id!==item.id)})}><Trash2 size={16}/></button>}</article>)}{!trip.items.some(x=>x.day===d)&&<p>Belum ada aktivitas. Tambahkan melalui formulir di atas.</p>}</section>)}
 </div><aside className="budget-panel"><div className="eyebrow">ANGGARAN BELUM LENGKAP</div><span>Subtotal tercatat / orang</span><h2>{money(total.perPerson)}</h2><p>Total {trip.people} orang: {money(total.total)}</p><p>Sudah dipesan: {money(total.paid)}</p>{trip.journey==='oneway'&&!trip.items.some(x=>x.category==='Pesawat'&&x.id!=='flight')&&<p className="city-warning">Belum termasuk tiket pulang.</p>}<p>Lengkapi biaya hotel, makan, transportasi, wisata, dokumen, bagasi, dan cadangan sebelum menentukan anggaran akhir.</p><button className="primary" disabled={busy} onClick={onSave}>Simpan perjalanan</button></aside></div></>;
}
