import ItemBooking from './item-booking';
import type {PartnerContext} from './partner-selection';
import RouteMap from './route-map';
import InfoNote from './info-note';
import AIItemDetails from './ai-item-details';
import FlightBooking from './flight-booking';
import {useState} from 'react';
import {Bookmark,Plus,Trash2} from 'lucide-react';
import {type Trip,type Item,money,addDays,costs,shortDate} from './travel-data';
import {FlightTimes} from './flight-search';
export default function WorldPlanner({trip,onChange,onSave,busy,dirty,onSearch}:{trip:Trip;onChange:(t:Trip)=>void;onSave:()=>void;busy:boolean;dirty:boolean;onSearch?:(kind:'hotels'|'transport',context:PartnerContext)=>void}){
 const [title,setTitle]=useState(''),[category,setCategory]=useState('Wisata'),[day,setDay]=useState(0),[price,setPrice]=useState(''),[time,setTime]=useState('10:00');
 const [dayStart,setDayStart]=useState(1),[view,setView]=useState('itinerary');
 const meta=trip.destinationMeta,total=costs(trip);
 function update(id:string,values:Partial<Item>){onChange({...trip,items:trip.items.map(x=>x.id===id?{...x,...values,userEdited:true,template:false,generated:false}:x)});}
 function add(e:React.FormEvent){e.preventDefault();if(!title.trim()||!Number.isFinite(Number(price))||Number(price)<0||Number(price)>1e9)return;onChange({...trip,items:[...trip.items,{id:crypto.randomUUID(),title:title.trim(),category,day,price:Number(price),time,paid:false,note:'Anggaran yang dimasukkan pengguna; per orang.'}]});setTitle('');setPrice('');}
 return <><div className="planner-title"><div><div className="eyebrow">MULAI DARI TIKET, LENGKAPI BERTAHAP</div><h1>{meta?.city||trip.destination}</h1><p>{meta?.country} · {shortDate(trip.start)} – {shortDate(addDays(trip.start,trip.days-1))} · {trip.people} orang</p><p>{dirty?'Belum disimpan':'Tersimpan'}</p></div><button className="primary" disabled={busy} onClick={onSave}><Bookmark size={18}/>{busy?'Menyimpan…':'Simpan itinerary'}</button></div>
 <InfoNote label="Informasi anggaran"><p className="city-warning">{trip.aiPlan?'Wisata, rekomendasi hotel dan transportasi AI ada pada itinerary harian. Subtotal belum mencakup harga yang belum diisi.':'Rekomendasi otomatis belum tersedia. Subtotal hanya menghitung item yang tercatat.'} Harga tiket tersimpan tidak diperbarui otomatis.</p></InfoNote>
 <nav className="planner-view" aria-label="Tampilan perjalanan"><button className="secondary" aria-pressed={view==='itinerary'} onClick={()=>setView('itinerary')}>Itinerary harian</button><button className="secondary" aria-pressed={view==='map'} onClick={()=>setView('map')}>Peta & rute</button></nav>{view==='map'?<RouteMap onSearch={onSearch} trip={trip} onChange={onChange}/>:<div className="planner-layout"><div>{trip.flight&&<section className="selected-flight"><FlightTimes f={trip.flight} origin={trip.origin} code={meta?.code||trip.destination}/><FlightBooking item={trip.items.find(x=>x.id==='flight')||{id:'flight',title:'Penerbangan',category:'Pesawat',price:0,paid:false,day:1,time:'',note:''}} trip={trip}/><p>Tautan untuk 1 dewasa. Periksa jumlah penumpang dan harga akhir di penyedia.</p></section>}
 <p>Atur penginapan, wisata, dan transportasi melalui pengaturan masing-masing hari.</p>
 {trip.days>14&&<div className="day-pagination"><button className="secondary" disabled={dayStart===1} onClick={()=>setDayStart(Math.max(1,dayStart-14))}>Hari sebelumnya</button><span>Hari {dayStart}–{Math.min(trip.days,dayStart+13)} dari {trip.days}</span><button className="secondary" disabled={dayStart+14>trip.days} onClick={()=>setDayStart(dayStart+14)}>Hari berikutnya</button></div>}{Array.from({length:Math.min(14,trip.days-dayStart+1)},(_,i)=>dayStart+i).map(d=><section className="day" key={d}><h3>Hari {d} · {shortDate(addDays(trip.start,d-1))}</h3><button className="secondary" aria-expanded={day===d} onClick={()=>setDay(day===d?0:d)}>Pengaturan hari {d}</button>{day===d&&<form className="world-item-form" onSubmit={add}><label>Kategori<select value={category} onChange={e=>setCategory(e.target.value)}>{['Wisata','Penginapan','Transportasi','Pesawat'].map(c=><option key={c}>{c}</option>)}</select></label><label>Nama tempat / aktivitas<input required maxLength={160} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Jam<input type="time" required value={time} onChange={e=>setTime(e.target.value)}/></label><label>Anggaran / orang (Rp)<input type="number" min="0" max="1000000000" required value={price} onChange={e=>setPrice(e.target.value)}/></label><button className="primary"><Plus size={16}/>Tambah</button></form>}{trip.items.filter(x=>x.day===d&&x.category!=='Makan').map(item=><article className="world-item" key={item.id}><div><label>Nama aktivitas<input aria-label={'Nama '+item.title} maxLength={160} value={item.title} onChange={e=>update(item.id,{title:e.target.value,place:e.target.value,geo:undefined,sourceUrl:undefined})}/></label><label>Jam<input aria-label={'Jam '+item.title} type="time" value={item.time} onChange={e=>update(item.id,{time:e.target.value})}/></label><p>{item.category} · {item.priceUnknown?'Harga belum diisi':item.paid?'Sudah dipesan · catatan pengguna':'Belum dipesan'}</p><AIItemDetails item={item} onSelectRoute={index=>{if(!item.paid)onChange({...trip,items:trip.items.map(x=>x.id===item.id?{...x,selectedRoute:index,userEdited:true}:x)});}}/><ItemBooking item={item} trip={trip} onSearch={onSearch}/></div><label>Biaya / orang<input aria-label={'Biaya '+item.title} type="number" min="0" max="1000000000" value={item.price} onChange={e=>{const n=Number(e.target.value);if(Number.isFinite(n)&&n>=0&&n<=1e9)update(item.id,{price:n,priceUnknown:false});}}/></label><label><input type="checkbox" checked={item.paid} onChange={e=>update(item.id,{paid:e.target.checked})}/> Sudah dipesan</label>{item.id!=='flight'&&<button className="icon-button" aria-label={'Hapus '+item.title} onClick={()=>onChange({...trip,items:trip.items.filter(x=>x.id!==item.id)})}><Trash2 size={16}/></button>}</article>)}{!trip.items.some(x=>x.day===d)&&<p>Belum ada aktivitas. Tambahkan melalui pengaturan hari ini.</p>}</section>)}
 </div><aside className="budget-panel"><div className="eyebrow">ANGGARAN BELUM LENGKAP</div><span>Subtotal tercatat / orang</span><h2>{money(total.perPerson)}</h2><p>Total {trip.people} orang: {money(total.total)}</p><p>Sudah dipesan: {money(total.paid)}</p>{trip.journey==='oneway'&&!trip.items.some(x=>x.category==='Pesawat'&&x.id!=='flight')&&<p className="city-warning">Belum termasuk tiket pulang.</p>}<p>Lengkapi biaya hotel, transportasi, wisata, dokumen, bagasi, dan cadangan sebelum menentukan anggaran akhir. Biaya makan tidak termasuk.</p><button className="primary" disabled={busy} onClick={onSave}>Simpan perjalanan</button></aside></div>}</>;
}
